env: 
    VUEDEX_TOKEN: ${{ secrets.VUEDEX_TOKEN }}
permissions:
      contents: write

name: Publish to gh-pages


on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install
    - run: sh deploy.sh
#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.VUEDEX_TOKEN }}
#         publish_dir: ./dist
