name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sh deploy.sh
#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.VUEDEX_TOKEN }}
#         publish_dir: ./dist
